server:
  port: 8080

spring:
  application:
    name: dnd_backend
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.dnd_backend.*
            use:
              type:
                headers: false
            value:
              default:
                type: com.example.dnd_backend.domain.events.DomainEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/dnd_backend?authSource=admin
      database: dnd_backend
