@URL=http://localhost:8080

### Create a character
POST {{ URL }}/characters
Content-Type: application/json

{
  "name": "Bob",
  "stats": {
    "strength": 18,
    "dexterity": 9,
    "constitution": 16,
    "intelligence": 8,
    "wisdom": 12,
    "charisma": 10
  }
}

### Create another character
POST {{ URL }}/characters
Content-Type: application/json

{
  "name": "Doug",
  "stats": {
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 8,
    "wisdom": 10,
    "charisma": 12
  }
}

### Update a character
PUT {{ URL }}/characters
Content-Type: application/json

{
  "name": "Doug",
  "stats": {
    "strength": 11,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 8,
    "wisdom": 10,
    "charisma": 12
  }
}

### Get all
GET {{ URL }}/characters

### GET specific
GET {{ URL }}/characters/Bob

### GET another specific
GET {{ URL }}/characters/Doug