@URL=http://localhost:8080

### Create a character
POST {{ URL }}/characters
Content-Type: application/json

{
  "name": "Bob",
  "stats": {
    "strength": 18,
    "dexterity": 9,
    "constitution": 16,
    "intelligence": 8,
    "wisdom": 12,
    "charisma": 10
  }
}

### Get all
GET {{ URL }}/characters

### GET specific
GET {{ URL }}/characters/Bob