package com.example.dnd_backend.persistence;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;

import java.util.HashSet;
import java.util.Set;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = {"name"})
public class ItemPersistenceDTO {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String name;
    private String description;
    private double weight;

    @ManyToMany(mappedBy = "inventory")
    private Set<PlayerCharacterPersistenceDTO> owners = new HashSet<>();

    // Custom constructor without ID for creation scenarios, Lombok's @AllArgsConstructor will include ID.
    // If needed, this can be kept, or rely on builder/setters after @NoArgsConstructor.
    // For now, relying on Lombok and removing this.
    // public ItemPersistenceDTO(String name, String description, double weight) {
    //     this.name = name;
    //     this.description = description;
    //     this.weight = weight;
    // }

    // Getters, Setters, equals, hashCode, toString will be generated by @Data
    // Handling of collections in equals/hashCode might need attention if issues arise.
} 